### ISSUE TITLE
您好，想问一下关于项目的实现方式

### ISSUE THREAD

**Issue by googs1025** [zwwhdls/csibuilder#9]
最近想研究研究代码生成器的项目，想问一下代码生成的主逻辑主要放在哪块呢？
感谢抽空回答 谢谢

**Comment by zwwhdls** [comment]
生成代码入口：https://github.com/zwwhdls/csibuilder/tree/main/pkg/plugins/scaffolds

项目主要参考了 kubebuilder，并对其进行了精简，也可以参考一下  kubebuilder 的实现。
